# Site settings
title: blog
email: lyj7694@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        Yunjae Lee's blog
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
github_username: yunjae2

# Build settings
markdown: kramdown

highlighter: rouge

plugins:
        - jekyll-paginate

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
        projects:
                output: true
                permalink: /projects/:path/

exclude: [poetry.md, portfolio.md]
